### ISSUE TITLE
component design doc

### ISSUE THREAD

**Issue by FE-Girl** [uxcore/uxcore-pickable-form-field#1]
- 该组件基于 uxcore-pickable 封装
- 支持的 props 如下：

| Name | Type | Required | Default | Comments |
| --- | --- | --- | --- | --- |
| jsxmultiple | boolean | optional | true | 是否支持多选 |
| jsxvalue | string/number | required | - | pickable Item 对应的值 |
| jsxtype | string | optional | normal | 样式风格，可选值为normal,simple |
| jsxdata | array | optional | - | 传入pickable的数据，例如：[{value:1,disabled:false,number:2,text:'显示文案'}] |

**Comment by eternalsky** [comment]
jsx 属于历史遗留问题，除了继承 formField 的部分，不要再加 jsx 了~
